
GET http://localhost:3000/todos/?search_q=%20&priority=HIGH&status=%20&todo=%20/
###
GET http://localhost:3000/todos/3/
###
POST http://localhost:3000/todos/
###

content-type : application/json
  {
      "todo": "LEARN FULLSTACK",
      "priority": "HIGH",
      "status": "TO DO"
  }

###
PUT http://localhost:3000/todos/4/
####
DELETE  http://localhost:3000/todos/1/